//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity
{
    using System;
    using System.Collections.Generic;
    
    public partial class brandyn
    {
        public int brandID { get; set; }
        public string snaks { get; set; }
        public string drinks { get; set; }
    }
}
